name: rss_bacano
description: A simple app to view RSS feeds.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  http: ^0.13.5
  webfeed: ^0.7.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  intl: ^0.17.0
  flutter_native_splash: ^2.0.0
  flutter_launcher_icons: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/image.png"


# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#39b54a'
  image: assets/image.png

flutter:

  uses-material-design: true

